environment:
  android:
    ndk: "21.4.7075529"  # ตั้งค่าเวอร์ชัน NDK ที่ต้องการใช้

scripts:
  # - sdkmanager --install "ndk;21.4.7075529"  # คำสั่งติดตั้ง NDK
  - sdkmanager --install "ndk;latest"
  - flutter clean
  - flutter pub get
  - flutter build apk
  # - echo "ndk.dir=$ANDROID_HOME/ndk/21.4.7075529" >> local.properties  # กำหนดเส้นทาง NDK โดยตรง
  - echo "NDK Path: $ANDROID_NDK_HOME"
  - echo "ndk.dir=$ANDROID_HOME/ndk-bundle" >> local.properties
  - flutter build apk --stacktrace


