environment:
  android:
    ndk: "21.4.7075529"  # ตั้งค่าเวอร์ชัน NDK ที่ต้องการใช้

scripts:
  - sdkmanager --install "ndk;21.4.7075529"  # คำสั่งติดตั้ง NDK
  - flutter clean
  - flutter pub get
  - flutter build apk
